AWSTemplateFormatVersion: 2010-09-09

Description: Assests para los laboratorios

Resources:
  DemoPipelineAssets:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://aws-ilt-courses.s3.amazonaws.com/pipeline-assets.yml
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  DemoSSHKeypair:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://aws-ilt-courses.s3.amazonaws.com/keypair-creation.yml
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  DemoDeploymentStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://aws-ilt-courses.s3.amazonaws.com/instancia.yml
      Parameters:
        SSHKeyName: !GetAtt DemoSSHKeypair.Outputs.SSHKeyName
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  DemoSecurityStackCICDTools:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://aws-ilt-courses.s3.amazonaws.com/security.yml
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

Outputs:
  WebServerPublicDNS:
    Description: 'Public DNS of EC2 instance'
    Value: !GetAtt DemoDeploymentStack.Outputs.WebServerPublicDNS

  WebServerElasticIP:
    Description: 'Elastic IP assigned to EC2'
    Value: !GetAtt DemoDeploymentStack.Outputs.WebServerElasticIP

  WebsiteURL:
    Value: !GetAtt DemoDeploymentStack.Outputs.WebsiteURL
    Description: Application URL
