AWSTemplateFormatVersion: 2010-09-09

Description: Assests para los laboratorios

Resources:
  # DevelopmentEnvironment:
  #   Type: AWS::Cloud9::EnvironmentEC2
  #   Properties:
  #     AutomaticStopTimeMinutes: 30
  #     Description: Ambiente de desarrollo para el curso AWSDEVOPS
  #     InstanceType: t2.micro
  #     Name: AWSDEVOPS-DevEnv
  #     OwnerArn: arn:aws:iam::864613434505:root
  #     SubnetId: subnet-8b377fc0
  #     Repositories:
  #       - PathComponent: awsdevops-course-demos-2021
  #         RepositoryUrl: https://git-codecommit.us-west-2.amazonaws.com/v1/repos/awsdevops-course-demos-2021

  #     Tags:
  #       - Key: Course
  #         Value: AWSDEVOPS

  S3AssestsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: awsdevops-demoartifacts
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Course
          Value: AWSDEVOPS

  SNSNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: awsdevops-demonotifications
      Subscription: 
        - Endpoint: domingo@allincloudservices.com
          Protocol: email
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  # DemoModule03Stack:
  #   Type: "AWS::CloudFormation::Stack"
  #   Properties:
  #     TemplateURL: https://aws-ilt-courses.s3.amazonaws.com/imageprocessing-demo.yml
  #     Tags: 
  #       - Key: Course
  #         Value: AWSDEVOPS

  DemoModule04DeploymentStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://aws-ilt-courses.s3.amazonaws.com/instancia.yml
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  DemoModule04SecurityStackCICDTools:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: https://aws-ilt-courses.s3.amazonaws.com/security.yml
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  LambdaRole: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: LambdaBuildingNotificationBasicRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: InlinePolicyOne
          PolicyDocument:
            Statement:
              - Sid: CodePipelinePolicy
                Effect: Allow
                Action: 
                  - codepipeline:PutJobFailureResult
                  - codepipeline:PutJobSuccessResult
                Resource:
                  - "*"
              - Sid: SNSPolicy
                Effect: Allow
                Action: 
                  - sns:Publish
                Resource:
                  - "*"
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  LambdaBuildingNotification:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        ZipFile: |
          var AWS = require('aws-sdk');

          var sns = new AWS.SNS({
            region: 'us-west-2'
          });

          var codepipeline = new AWS.CodePipeline({
            region: 'us-west-2'
          });

          exports.handler = (event, context, callback) => {
              var jobId = event["CodePipeline.job"].id;
              
              sns.publish({
                TopicArn: 'arn:aws:sns:us-west-2:864613434505:awsdevops-demonotifications',
                Message: 'Se ha iniciado una compilación \n' + JSON.stringify(event),
                Subject: 'Building in process'
              }, function (err, response) {
                if (err) return console.log(err);
                console.log(response);
                codepipeline.putJobSuccessResult({ jobId: jobId }, function(err, data) {
                    if(err) {
                        context.fail(err);      
                    } else {
                        context.succeed();      
                    }
                });
              });
          }; 
      FunctionName: awsdevops-democodepipeline
      Handler: index.handler
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Tags: 
        - Key: Course
          Value: AWSDEVOPS
      Timeout: 3

Outputs:
  WebServerPublicDNS:
    Description: 'Public DNS of EC2 instance'
    Value: !GetAtt DemoModule04DeploymentStack.Outputs.WebServerPublicDNS

  WebServerElasticIP:
    Description: 'Elastic IP assigned to EC2'
    Value: !GetAtt DemoModule04DeploymentStack.Outputs.WebServerElasticIP

  WebsiteURL:
    Value: !GetAtt DemoModule04DeploymentStack.Outputs.WebsiteURL
    Description: Application URL
