AWSTemplateFormatVersion: 2010-09-09

Description: Assests para los laboratorios

Resources:
  S3AssestsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Delete
    Properties:
      BucketName: !Sub awsdevops-demoartifacts-${AWS::Region}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: Course
          Value: AWSDEVOPS

  SNSNotificationsTopic:
    Type: AWS::SNS::Topic
    Properties: 
      TopicName: awsdevops-demonotifications
      Subscription: 
        - Endpoint: domingo@allincloudservices.com
          Protocol: email
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  LambdaRole: 
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: InlinePolicyOne
          PolicyDocument:
            Statement:
              - Sid: CodePipelinePolicy
                Effect: Allow
                Action: 
                  - codepipeline:PutJobFailureResult
                  - codepipeline:PutJobSuccessResult
                Resource:
                  - "*"
              - Sid: SNSPolicy
                Effect: Allow
                Action: 
                  - sns:Publish
                Resource:
                  - "*"
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  LambdaBuildingNotification:
    Type: AWS::Lambda::Function
    Properties: 
      Code: 
        ZipFile: 
          !Sub |
          var AWS = require('aws-sdk');

          var sns = new AWS.SNS();

          var codepipeline = new AWS.CodePipeline();

          exports.handler = (event, context, callback) => {
              var jobId = event["CodePipeline.job"].id;
              console.log(jobId);
              sns.publish({
                TopicArn: 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:awsdevops-demonotifications',
                Message: 'Se ha iniciado una compilación \n' + JSON.stringify(event),
                Subject: 'Building in process'
              }, function (err, response) {
                if (err) {
                  codepipeline.putJobFailResult({ jobId: jobId }, function(err, data) {
                    if(err) {
                        context.fail(err);      
                    } else {
                        context.succeed(data);      
                    }
                  });
                  return console.log(err);
                }
                codepipeline.putJobSuccessResult({ jobId: jobId }, function(err, data) {
                    if(err) {
                        context.fail(err);      
                    } else {
                        context.succeed(data);      
                    }
                });
                console.log(response);
              });
          }; 
      FunctionName: awsdevops-democodepipeline
      Handler: index.handler
      MemorySize: 128
      PackageType: Zip
      Role: !GetAtt LambdaRole.Arn
      Runtime: nodejs12.x
      Tags: 
        - Key: Course
          Value: AWSDEVOPS
      Timeout: 3

