AWSTemplateFormatVersion: '2010-09-09'

Description: Roles para los CI/CD tools de la demo modulo04

Resources:
  CodeBuildPolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: CodeBuildBasicServiceRolePolicy
      PolicyDocument:
        Statement:
          - Sid: CloudWatchLogsPolicy
            Effect: Allow
            Action: 
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - "*"
          - Sid: CodeCommitPolicy
            Effect: Allow
            Action: 
              - codecommit:GitPull
            Resource:
              - "*"
          - Sid: S3GetObjectPolicy
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
            Resource:
              - "*"
          - Sid: S3PutObjectPolicy
            Effect: Allow
            Action:
              - s3:PutObject
            Resource:
              - "*"
          - Sid: ECRPullPolicy
            Effect: Allow
            Action:
              - ecr:BatchCheckLayerAvailability
              - ecr:GetDownloadUrlForLayer
              - ecr:BatchGetImage
            Resource:
              - "*"
          - Sid: ECRPushPolicy
            Effect: Allow
            Action:
              - ecr:InitiateLayerUpload
              - ecr:UploadLayerPart
              - ecr:CompleteLayerUpload
              - ecr:PutImage
            Resource:
              - "*"
          - Sid: ECRAuthPolicy
            Effect: Allow
            Action:
              - ecr:GetAuthorizationToken
            Resource:
              - "*"
          - Sid: S3BucketIdentity
            Effect: Allow
            Action:
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Resource:
              - "*"
      Roles:
        - !Ref CodeBuildRole

  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeBuildBasicServiceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

  CodeDeployRole: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodeDeployBasicServiceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
        - arn:aws:iam::aws:policy/AWSCodeDeployRoleForECS
      Tags: 
        - Key: Course
          Value: AWSDEVOPS
  
  CodePipelinePolicy:
    Type: AWS::IAM::Policy
    Properties: 
      PolicyName: CodePipelineBasicServiceRolePolicy
      PolicyDocument:
        Statement:
          - Sid: PassRolePolicy
            Effect: Allow
            Action: 
              - iam:PassRole
            Condition:
              StringEqualsIfExists:
                iam:PassedToService:
                - cloudformation.amazonaws.com
                - elasticbeanstalk.amazonaws.com
                - ec2.amazonaws.com
                - ecs-tasks.amazonaws.com
            Resource:
              - "*"
          - Sid: CodeCommitPolicy2
            Effect: Allow
            Action: 
              - codecommit:CancelUploadArchive
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
            Resource:
              - "*"
          - Sid: CodeDeployPolicy
            Effect: Allow
            Action:
              - codedeploy:CreateDeployment
              - codedeploy:GetApplication
              - codedeploy:GetApplicationRevision
              - codedeploy:GetDeployment
              - codedeploy:GetDeploymentConfig
              - codedeploy:RegisterApplicationRevision
            Resource:
              - "*"
          - Sid: CodeStarConnectionPolicy
            Effect: Allow
            Action:
              - codestar-connections:UseConnection
            Resource:
              - "*"
          - Sid: MixedPolicy
            Effect: Allow
            Action:
              - elasticbeanstalk:*
              - ec2:*
              - elasticloadbalancing:*
              - autoscaling:*
              - cloudwatch:*
              - s3:*
              - sns:*
              - cloudformation:*
              - rds:*
              - sqs:*
              - ecs:*
            Resource:
              - "*"
          - Sid: LambdaPolicy
            Effect: Allow
            Action:
              - lambda:InvokeFunction
              - lambda:ListFunctions
            Resource:
              - "*"
          - Sid: OpsWorksPolicy
            Effect: Allow
            Action:
              - opsworks:CreateDeployment
              - opsworks:DescribeApps
              - opsworks:DescribeCommands
              - opsworks:DescribeDeployments
              - opsworks:DescribeInstances
              - opsworks:DescribeStacks
              - opsworks:UpdateApp
              - opsworks:UpdateStack
            Resource:
              - "*"
          - Sid: CloudFormationPolicy
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
            Resource:
              - "*"
          - Sid: CodeBuildPolicy2
            Effect: Allow
            Action:
              - codebuild:BatchGetBuilds
              - codebuild:StartBuild
            Resource:
              - "*"
          - Sid: DeviceFarmPolicy
            Effect: Allow
            Action:
              - devicefarm:ListProjects
              - devicefarm:ListDevicePools
              - devicefarm:GetRun
              - devicefarm:GetUpload
              - devicefarm:CreateUpload
              - devicefarm:ScheduleRun
            Resource:
              - "*"
          - Sid: ServiceCatalogPolicy
            Effect: Allow
            Action:
              - servicecatalog:ListProvisioningArtifacts
              - servicecatalog:CreateProvisioningArtifact
              - servicecatalog:DescribeProvisioningArtifact
              - servicecatalog:DeleteProvisioningArtifact
              - servicecatalog:UpdateProduct
            Resource:
              - "*"
          - Sid: CloudFormationVPolicy
            Effect: Allow
            Action:
              - cloudformation:ValidateTemplate
            Resource:
              - "*"
          - Sid: ECRPolicy
            Effect: Allow
            Action:
              - ecr:DescribeImages
            Resource:
              - "*"
          - Sid: StepFunctionsPolicy
            Effect: Allow
            Action:
              - states:DescribeExecution
              - states:DescribeStateMachine
              - states:StartExecution
            Resource:
              - "*"
      Roles:
        - !Ref CodePipelineRole
  
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CodePipelineBasicServiceRole
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      Tags: 
        - Key: Course
          Value: AWSDEVOPS

Outputs:
  CodeBuildRoleArn:
    Value: !GetAtt CodeBuildRole.Arn
    Export:
      Name: Demo-AWSDEVOPS-CodeBuildRoleArn

  CodeDeployRoleArn:
    Value: !GetAtt CodeDeployRole.Arn
    Export:
      Name: Demo-AWSDEVOPS-CodeDeployRoleArn

  CodePipelineRoleArn:
    Value: !GetAtt CodePipelineRole.Arn
    Export:
      Name: Demo-AWSDEVOPS-CodePipelineRoleArn