AWSTemplateFormatVersion: '2010-09-09'

Description: CFN 101 Workshop - Lab 02 Resources.

Resources:
  WebServerInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00a1270ce1e007c27 # This ImageId will only work in the London region
      InstanceType: t2.micro
